# 01_design_strategy_planning

Notebook UI for planning a multi-round enzyme design workflow using user constraints and optional prior literature-review context.

## Python Path Setup
Ensure project-root imports work whether Jupyter starts from repo root or `notebooks/`.

In [1]:
from pathlib import Path
import os
import sys

cwd = Path.cwd().resolve()
repo_root = cwd.parent if cwd.name == "notebooks" else cwd
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
src_root = repo_root / "src"
if src_root.exists() and str(src_root) not in sys.path:
    sys.path.insert(0, str(src_root))

## Imports
Load helper functions for setup, optional literature-context loading, planning prompt generation, and thread persistence.

In [2]:
import importlib
import agentic_protein_design.steps.design_strategy_planning as dsp

dsp = importlib.reload(dsp)

default_user_inputs = dsp.default_user_inputs
init_thread = dsp.init_thread
load_literature_context = dsp.load_literature_context
generate_design_strategy_plan = dsp.generate_design_strategy_plan
reflect_and_regenerate_design_strategy_plan = dsp.reflect_and_regenerate_design_strategy_plan
design_strategy_reflection_prompt = dsp.design_strategy_reflection_prompt
save_design_strategy_plan = dsp.save_design_strategy_plan
save_design_strategy_workflow_steps = dsp.save_design_strategy_workflow_steps
persist_thread_update = dsp.persist_thread_update
setup_data_root = dsp.setup_data_root
get_step_processed_dir = dsp.get_step_processed_dir

from agentic_protein_design.core import apply_notebook_markdown_style

# Slightly smaller rendered markdown text in outputs.
apply_notebook_markdown_style(font_size_px=14, line_height=1.4)

## User Inputs
Configure dataset root, thread key, optional literature context key, and planning requirements.

In [3]:
root_key = "examples"
existing_thread_key = 'design_strategy_planning_4b3ab33f0d634e4a85ce73f259eda102'

user_inputs = {
    "enzyme_family": "unspecific peroxygenases (UPOs)",
    "seed_sequences": ["CviUPO"],
    "reactions_of_interest": "peroxygenation of aromatics",
    "substrates_of_interest": ["Veratryl alcohol", "Naphthalene", "NBD", "ABTS", "S82"],
    "application_context": "biocatalysis and green chemistry",
    "constraints": ["H2O2 tolerance", "stability", "expression host compatibility"],
    "design_type_preference": "mutants_of_backbone",
    "backbone_protein": "CviUPO",
    "library_types": [
        "targeted_mutation_set",
        "site_saturation_mutagenesis",
        "combinatorial_library",
    ],
    "num_design_rounds": 3,
    "design_targets": [
        "increase peroxygenative mono-oxidation selectivity",
        "reduce over-oxidation",
        "maintain catalytic activity",
        "maintain or improve stability",
    ],
    "use_binding_pocket_analysis_step": True,
    "available_tools": [
        "sequence database search and alignment",
        "conservation_analysis analysis",
        "Boltz-2 docking/pose assessment",
        "OpenMM/YASARA ddG_bind simulations",
        "Pythia stability prediction",
        "protein language model zero-shot scoring",
        "BoltzGen or RFdiffusion2 de novo generation",
        "supervised surrogate models with OHE/PLM embeddings",
    ],
    # Optional: key format is {tag}_{thread_id}, e.g. literature_review_<thread_id>
    "literature_context_thread_key": "literature_review_d762a72ec7f04bec9b66ccd3aac21b91",
    "llm_model": "gpt-5.2",
    "llm_temperature": 0.2,
}

# Optional: reset all fields from helper defaults

## Setup Runtime Context
Initialize data directories and active chat thread from the values above.

In [4]:
data_root, resolved_dirs = setup_data_root(root_key)
step_processed_dir = get_step_processed_dir(resolved_dirs)
thread, threads_preview = init_thread(root_key, existing_thread_key)
thread_id = thread["thread_id"]
data_root, step_processed_dir, thread_id

(PosixPath('/Users/charmainechia/Documents/projects/agentic-protein-design/examples'),
 PosixPath('/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning'),
 '4b3ab33f0d634e4a85ce73f259eda102')

## Optional Literature Context
Load prior literature-review context (thread history + referenced output files) when a thread key is provided.

In [5]:
literature_context_thread_key = str(user_inputs.get("literature_context_thread_key", "")).strip() or None
context_result = load_literature_context(literature_context_thread_key, max_chars_per_file=40000)
literature_context = str(context_result.get("context_text", ""))
literature_context_bundle = context_result.get("context_bundle")
len(literature_context), context_result.get("context_error", "")

engineering_strategy = ((literature_context_bundle or {}).get("referenced_json_objects") or {}).get("engineering_strategy", {})

(88517, '')

## Generate Design Strategy Plan
Run planning LLM call using user requirements and optional literature context, then save markdown output.

In [6]:
plan_outputs = generate_design_strategy_plan(
    user_inputs,
    literature_context=literature_context,
    engineering_strategy=engineering_strategy,
)
design_plan = plan_outputs['strategy_writeup']
workflow_steps_json = plan_outputs['workflow_steps_json']

# Save/overwrite both artifacts from initial generation.
out_design_plan = save_design_strategy_plan(design_plan, step_processed_dir)
out_workflow_steps = save_design_strategy_workflow_steps(workflow_steps_json, step_processed_dir)

{
    "workflow_step_count": len(workflow_steps_json),
    "has_strategy_writeup": bool(design_plan.strip()),
    "design_plan_path": str(out_design_plan),
    "workflow_steps_path": str(out_workflow_steps),
}

### Design Strategy LLM Call (Prompt 2 Writeup)

<details><summary>Prompt</summary>

```text

You are an expert computational protein engineer and workflow architect.

Goal:
Convert project requirements into an executable multi-step protein-design workflow.

Inputs:
- user_inputs_json: project requirements and design preferences
- literature_context (optional): prior literature synthesis and linked full-text summaries

Requirements:
1) Build an end-to-end strategy with clear phases (data, hypothesis, design, evaluation, iteration).
2) Explicitly choose and justify design mode:
   - de novo design, backbone-focused mutant design, or hybrid
3) Propose library strategy aligned to objectives:
   - exact targeted sequences, random mutagenesis, site-saturation mutagenesis (SSM), combinatorial library
4) Plan across the specified number of rounds and approximate size of each round, with clear decision gates and progression criteria.
5) Include concrete implementation details:
   - tools/models to run per step
   - expected inputs/outputs per step
   - fallback or alternative path if a step fails
6) Integrate relevant existing process modules when useful (for example binding_pocket_analysis).
7) Prioritize feasibility, information gain per round, and tractable experimental burden.

Available tool categories (non-exhaustive):
- sequence database search and alignment -> conservation_analysis analysis
- receptor-ligand docking / structure prediction (for example Boltz-2)
- ddG_bind style simulations (for example OpenMM or YASARA)
- stability prediction (for example Pythia)
- zero-shot scoring from protein language models
- de novo generation (for example BoltzGen or RFdiffusion2)
- supervised surrogate models (for example OHE/PLM embeddings + constrained acquisition)


PROJECT REQUIREMENTS SNAPSHOT
- enzyme_family: unspecific peroxygenases (UPOs)
- seed_sequences: CviUPO
- reactions_of_interest: peroxygenation of aromatics
- design_type_preference: mutants_of_backbone
- backbone_protein: CviUPO
- library_types: targeted_mutation_set; site_saturation_mutagenesis; combinatorial_library
- num_design_rounds: 3
- design_targets: increase peroxygenative mono-oxidation selectivity; reduce over-oxidation; maintain catalytic activity; maintain or improve stability
- constraints: H2O2 tolerance; stability; expression host compatibility
- available_tools: sequence database search and alignment; conservation_analysis analysis; Boltz-2 docking/pose assessment; OpenMM/YASARA ddG_bind simulations; Pythia stability prediction; protein language model zero-shot scoring; BoltzGen or RFdiffusion2 de novo generation; supervised surrogate models with OHE/PLM embeddings



PART 2: Write a concise human-readable strategy summary using:
1) the original context, and
2) the PART 1 JSON workflow.

Output contract:
- Return ONLY markdown prose.
- Keep it succinct and action-oriented (target ~350-700 words).

Required sections:
1. Overall strategy (5-8 bullets)
2. Design choices and assumptions (short)
3. Step-by-step execution summary
   - one compact paragraph per step from PART 1
   - if a step proposes using a foundational Protein Language Model or Structure-prediction model is proposed, recommend which models to use.
   - if a step proposes using a supervised Machine Learning model trained on screening data, propose the model type and input features to use (ok to provide options)
4. Decision gates and immediate next actions (short)

```
</details>

#### Response

(Full strategy shown below in compact view.)

### Human-Readable Strategy (Prompt 2)

## Overall strategy (5–8 bullets)

- Use **backbone-focused mutant design on CviUPO** to tune **access-channel geometry and pocket polarity**, the dominant levers for aromatic chemo-/regioselectivity in UPOs, while preserving the heme-thiolate catalytic core.
- Run a **dual-activity/selectivity screening logic** each round: favor **peroxygenation** (e.g., NBD turnover; desired aromatic mono-oxidation products) and penalize **peroxidation/overoxidation** (e.g., ABTS oxidation; naphthol → naphthoquinone drift).
- Front-load **evolutionary priors** (homolog mining + conservation) to protect catalytic/structural residues and focus mutagenesis on mutable channel residues.
- Build a **structure + binding_pocket_analysis module** (Boltz-2 + pocket/channel mapping + docking) to generate pose hypotheses and pick mutation sites.
- Execute **3 rounds** with increasing sophistication: (1) small targeted single mutants for information gain, (2) SSM at validated hotspots + capped combinatorials for epistasis, (3) **model-guided recombinants** using screening data + physics/PLM priors.
- Maintain feasibility by capping libraries to **~48 → ~192 → ~48** variants, compatible with microtiter expression and analytical follow-up.
- Include explicit **fallbacks**: if homolog search/docking fails, proceed with literature-known channel hotspots (e.g., CviUPO 88/158); if no hits after Round 2/3, trigger a **hybrid** (loop/channel redesign via BoltzGen/RFdiffusion2 or switch to a better-expressing homolog).

## Design choices and assumptions (short)

- **Design mode chosen:** *backbone-focused mutant design* (primary), with an optional **hybrid fallback** only if CviUPO cannot meet selectivity/stability/H₂O₂ tolerance simultaneously. This matches the stated preference and UPO precedent that channel reshaping drives selectivity.
- Assumes you can provide a **CviUPO FASTA/accession** and can measure at least one **peroxygenation proxy (NBD)** and one **peroxidation proxy (ABTS)** plus a product readout on aromatics (e.g., naphthol/quinone ratio).

## Step-by-step execution summary

**Step 1 — Load inputs and seed sequence.** The workflow initializes a run state and enforces a hard gate on having the **CviUPO sequence**. Input: `input_data.json` plus `CviUPO.fasta` (or it writes a stub). Output: `state_step1.json`. If the sequence is missing, the pipeline stops early with a clear action: supply FASTA and rerun.

**Step 2 — Mine homologs and conservation.** Run sequence database search + MSA and compute per-position conservation to identify **protected residues** and **mutable channel positions**. Inputs: seed FASTA. Outputs: `homologs.fasta`, `upo_alignment.a3m`, `conservation.json`, `state_step2.json`. Fallback: if search fails/empty, proceed with seed-only alignment (lower confidence but unblocks design).

**Step 3 — Structure model + binding_pocket_analysis + docking.** Predict a CviUPO structure (Boltz-2) and run **binding_pocket_analysis** to enumerate pocket/channel residues; dock key aromatics (where SMILES available) to generate contact/pose hypotheses. Inputs: FASTA + substrate list. Outputs: `CviUPO_boltz2.pdb`, `binding_pocket.json`, `docking_results.json`, `state_step3.json`. If docking is unreliable, still use pocket/channel residue lists for mutagenesis targeting. Recommended models: **Boltz-2** for structure/pose assessment.

**Step 4 — Round 1 targeted mutation set (~48).** Build a small **single-mutant** library at up to ~8 channel/pocket positions (excluding highly conserved sites), using a restricted amino-acid set for sterics/polarity tuning. Score variants with **PLM zero-shot** and **Pythia stability** to avoid destabilizing moves. Outputs: `round1_targeted_variants.json`, `state_step4.json`. Recommended PLMs: **ESM2** or **ProtT5** for zero-shot ΔlogP; stability: **Pythia**.

**Step 5 — Round 2 SSM + combinatorial (~192).** After Round 1 screening, pick **3–4 best positions** and run **SSM** (filtered by Pythia), plus a capped **combinatorial recombination** of top single mutations. Optionally score combos with **OpenMM/YASARA ddG_bind** against a representative aromatic (e.g., naphthalene) to prioritize productive binding/orientation. Outputs: `round2_library.json`, `state_step5.json`. If Round 1 data are missing, it still proposes a conservative diverse Round 2.

**Step 6 — Round 3 model-guided refinement (~48).** Train a supervised surrogate if enough Round 2 data exist (≥~30 labeled variants) and propose recombinants balancing selectivity/activity/stability/H₂O₂ tolerance; otherwise rank by ddG_bind + Pythia + PLM priors. Outputs: `round3_final_panel.json`, `state_step6.json`. Recommended supervised model: **gradient-boosted trees (XGBoost/LightGBM)** or **regularized regression** on **PLM embeddings (ESM2/ProtT5) + one-hot mutation features**, optionally adding computed features (Pythia ddG, ddG_bind).

## Decision gates and immediate next actions (short)

- **Gate 0 (now):** Provide **CviUPO FASTA/accession** and confirm expression host + assay plan (NBD/ABTS + at least one LC/GC product ratio on naphthalene/veratryl alcohol).
- **Gate 1 (post-R1):** Advance variants with improved **peroxygenation:peroxidation** proxy and no major activity/stability loss; choose 3–4 hotspot positions for SSM.
- **Gate 2 (post-R2):** Advance variants that improve **mono-oxidation selectivity** (e.g., higher naphthol/quinone; reduced overoxidation) while meeting **H₂O₂ tolerance** and stability/expression thresholds.
- **Gate 3 (post-R3):** Finalize **3–5 leads**; if none beat WT on the full objective, trigger the defined **hybrid fallback** (channel-loop redesign via BoltzGen/RFdiffusion2 or switch to a better-expressing homolog from Step 2).

### Structured Workflow Plan (Prompt 1 JSON as table)

,step_index,step_name,tools,description,python_code_preview
0,1,load_inputs_and_seed_sequence,sequence database search and alignment,"Loads project requirements, locates/creates th...","import json, os, re from pathlib import Path ..."
1,2,mine_homologs_and_conservation,"sequence database search and alignment, conser...","Searches for UPO homologs, builds an MSA, and ...","import json, os, re from pathlib import Path ..."
2,3,structure_model_and_binding_pocket_analysis,Boltz-2 docking/pose assessment,"Predicts a CviUPO structure, runs binding pock...","import json, os from pathlib import Path OUTD..."
3,4,generate_round1_targeted_mutation_set,"protein language model zero-shot scoring, Pyth...",Builds a Round-1 targeted single-mutant librar...,"import json, os, itertools from pathlib import..."
4,5,round2_ssm_and_combinatorial_design,"OpenMM/YASARA ddG_bind simulations, Pythia sta...",Consumes Round-1 results (if available) to cho...,"import json, os, random from pathlib import Pa..."
5,6,round3_model_guided_refinement_and_final_panel,supervised surrogate models with OHE/PLM embed...,Trains/uses a supervised surrogate (when enoug...,"import json, os, random from pathlib import Pa..."

{'workflow_step_count': 6,
 'has_strategy_writeup': True,
 'design_plan_path': '/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning/design_strategy_planning.md',
 'workflow_steps_path': '/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning/design_strategy_planning_workflow_steps.json'}

## Reflect / Critique and Regenerate Plan

Use this step to critique the initial plan, incorporate optional user feedback, and rewrite a single improved final plan for saving/persistence.

In [7]:
user_feedback = {
    "plan_reflection_user_feedback": "",  # Optional: free-text critique/changes you want the LLM to apply
    "plan_reflection_prompt_override": "",  # Optional: replace default reflection prompt (part 2)
}

reflection_user_feedback = str(user_feedback.get("plan_reflection_user_feedback", "")).strip()
reflection_prompt = str(user_feedback.get("plan_reflection_prompt_override", "")).strip() or design_strategy_reflection_prompt

plan_outputs = reflect_and_regenerate_design_strategy_plan(
    user_inputs=user_inputs,
    original_prompt_1_output=workflow_steps_json,
    original_prompt_2_output=design_plan,
    literature_context=literature_context,
    engineering_strategy=engineering_strategy,
    user_feedback=reflection_user_feedback,
    critique_prompt=reflection_prompt,
)

# Update in-memory copies
design_plan = plan_outputs['strategy_writeup']
workflow_steps_json = plan_outputs['workflow_steps_json']

# Overwrite saved artifacts with improved outputs
out_design_plan = save_design_strategy_plan(design_plan, step_processed_dir)
out_workflow_steps = save_design_strategy_workflow_steps(workflow_steps_json, step_processed_dir)

{
    "refined_workflow_step_count": len(workflow_steps_json),
    "design_plan_path": str(out_design_plan),
    "workflow_steps_path": str(out_workflow_steps),
}

Critique and revisions summary:
- **State management was restructured** from a loose set of fields into a clearer “single source of truth” (`project/files/gates/priors/round_plans`), improving traceability and reducing ambiguity about inputs/outputs across steps.
- **Design-mode choice and assay logic were made explicit at initialization** (recorded in Step 1), because they are core requirements that drive downstream decisions (backbone-focused primary; NBD vs ABTS + product ratio as the selection objective).
- **Hard gating was tightened and clarified**: seed-sequence availability now uses a stronger length sanity check and a dedicated `gates` block with an explicit Gate0 action, preventing wasted MSA/structure work when FASTA is missing.
- **Evolutionary and structural “do-not-mutate” logic was formalized** by persisting protected positions (entropy threshold) and adding structure-derived catalytic/heme-proximal protection notes, so mutation masks are justified rather than ad hoc.
- **Round 2 was split into a decision step + build step** (new Step 5 for results ingestion/hotspot selection, then Step 6 for library construction), because hotspot selection should be contingent on real Round 1 data rather than embedded inside library generation.
- **Hybrid/de novo redesign was moved from implicit fallback to an explicit, user-triggered contingency step** (new Step 8), clarifying that de novo methods are not part of the primary plan and only activate if the campaign stalls.

### Design Strategy Reflection / Rewrite

<details><summary>Prompt</summary>

```text

You are an expert computational protein engineer and workflow architect.

Goal:
Convert project requirements into an executable multi-step protein-design workflow.

Inputs:
- user_inputs_json: project requirements and design preferences
- literature_context (optional): prior literature synthesis and linked full-text summaries

Requirements:
1) Build an end-to-end strategy with clear phases (data, hypothesis, design, evaluation, iteration).
2) Explicitly choose and justify design mode:
   - de novo design, backbone-focused mutant design, or hybrid
3) Propose library strategy aligned to objectives:
   - exact targeted sequences, random mutagenesis, site-saturation mutagenesis (SSM), combinatorial library
4) Plan across the specified number of rounds and approximate size of each round, with clear decision gates and progression criteria.
5) Include concrete implementation details:
   - tools/models to run per step
   - expected inputs/outputs per step
   - fallback or alternative path if a step fails
6) Integrate relevant existing process modules when useful (for example binding_pocket_analysis).
7) Prioritize feasibility, information gain per round, and tractable experimental burden.

Available tool categories (non-exhaustive):
- sequence database search and alignment -> conservation_analysis analysis
- receptor-ligand docking / structure prediction (for example Boltz-2)
- ddG_bind style simulations (for example OpenMM or YASARA)
- stability prediction (for example Pythia)
- zero-shot scoring from protein language models
- de novo generation (for example BoltzGen or RFdiffusion2)
- supervised surrogate models (for example OHE/PLM embeddings + constrained acquisition)


PROJECT REQUIREMENTS SNAPSHOT
- enzyme_family: unspecific peroxygenases (UPOs)
- seed_sequences: CviUPO
- reactions_of_interest: peroxygenation of aromatics
- design_type_preference: mutants_of_backbone
- backbone_protein: CviUPO
- library_types: targeted_mutation_set; site_saturation_mutagenesis; combinatorial_library
- num_design_rounds: 3
- design_targets: increase peroxygenative mono-oxidation selectivity; reduce over-oxidation; maintain catalytic activity; maintain or improve stability
- constraints: H2O2 tolerance; stability; expression host compatibility
- available_tools: sequence database search and alignment; conservation_analysis analysis; Boltz-2 docking/pose assessment; OpenMM/YASARA ddG_bind simulations; Pythia stability prediction; protein language model zero-shot scoring; BoltzGen or RFdiffusion2 de novo generation; supervised surrogate models with OHE/PLM embeddings



You are reviewing previously generated planning artifacts:
1) a human-readable strategy writeup (Prompt 2 output), and
2) a structured workflow JSON list (Prompt 1 output).

Task:
1) Critique consistency and quality across both artifacts:
   - gaps, weak assumptions, missing decision gates, feasibility risks
   - mismatches between workflow JSON steps and writeup narrative
   - missing or unclear implementation details in either artifact
2) Incorporate explicit user feedback if provided.
3) Regenerate an improved human-readable plan that is aligned with the workflow JSON.

Important output constraint:
- Return ONLY the rewritten final plan.
- Do NOT include a separate critique section.
- Do NOT include "old plan vs new plan" comparison.
- Keep the same overall output structure used for design strategy planning.

```
</details>

#### Response

(Refined strategy shown below in compact view.)

### Refined Strategy (After Reflection)

## Overall strategy (5–8 bullets)

- Use **backbone-focused mutant design on CviUPO** (primary mode) to tune **access-channel geometry, pocket polarity, and product egress**, which are the dominant levers for **aromatic mono-oxidation selectivity vs overoxidation** in UPOs, while preserving the heme-thiolate catalytic core.
- Run a **dual selectivity screen** each round to explicitly separate desired **peroxygenation (2e⁻ oxygen transfer)** from undesired **peroxidation/1e⁻ radical chemistry**:
  - **NBD** as a peroxygenation proxy (positive selection)
  - **ABTS** as a peroxidation proxy (negative selection)
  - plus **product selectivity** on aromatics (e.g., **naphthalene: 1‑naphthol vs 1,4‑naphthoquinone** by LC/GC).
- Front-load **evolutionary priors** (homolog mining + MSA conservation) to (i) protect catalytic/structural residues and (ii) highlight mutable tunnel residues; combine with **structure-derived pocket/channel residue lists**.
- Build a **structure + binding_pocket_analysis module** (Boltz‑2 structure prediction + pocket/channel mapping + docking) to generate actionable residue sets and pose hypotheses for aromatic substrates (naphthalene, veratryl alcohol, NBD).
- Execute **3 rounds** with increasing information content and controlled experimental burden:
  **Round 1** targeted single mutants (~48) → **Round 2** SSM at validated hotspots + capped combinatorials (~192) → **Round 3** model-guided recombinants (~48).
- Maintain feasibility with explicit **decision gates** and library caps (**~48 → ~192 → ~48**) compatible with microtiter expression and analytical follow-up.
- Keep **hybrid/de novo** methods strictly as a **contingency**: if CviUPO backbone mutagenesis cannot satisfy selectivity + activity + stability + H₂O₂ tolerance + expression, trigger **hybrid channel-loop redesign** (RFdiffusion2/BoltzGen) or **backbone switch** to a better-expressing homolog mined in Step 2.

---

## Design choices and assumptions (short)

- **Design mode chosen:** **backbone-focused mutant design** (explicitly recorded in `state_step1.json`).
  **Justification:** user preference is mutants_of_backbone; UPO aromatic selectivity is repeatedly driven by **access-channel/pocket mutations** (literature precedent), and this mode best preserves catalytic machinery and expression/stability risk profile.
  **Fallback mode:** **hybrid** (loop/channel redesign or backbone switch) only if the campaign stalls after Round 2/3.
- **Key assumptions / hard dependencies:**
  - You can provide a **CviUPO FASTA/accession** (Gate 0 hard stop if missing).
  - You can measure at least: **NBD rate**, **ABTS rate**, and **one aromatic product ratio** (naphthol vs quinone or analogous overoxidation marker), plus basic **activity/expression** and at least one **stability/H₂O₂ tolerance** readout.

---

## Step-by-step execution summary

### Step 1 — Initialize project state + hard gate on seed sequence (Gate 0)
**Goal:** create a single source of truth and prevent downstream work without the actual CviUPO sequence.
- **Tools/models:** none (state initialization + file checks).
- **Inputs:** `input_data.json`; expected `CviUPO.fasta` (or it writes a stub).
- **Outputs:** `workflow_out/state_step1.json`, `workflow_out/CviUPO.fasta` (stub if missing).
- **Decision gate (hard):** `seed_sequence_available == True` (sequence length sanity check).
- **If fails (fallback):** provide FASTA/accession in `workflow_out/CviUPO.fasta` and rerun.

---

### Step 2 — Homolog mining + MSA + conservation (UPObase-scale triage)
**Goal:** derive evolutionary priors to protect essential residues and focus mutagenesis on permissive sites.
- **Tools/models:** sequence DB search + alignment; `conservation_analysis`.
- **Inputs:** seed FASTA from Step 1.
- **Process:**
  - Mine homologs (e.g., UniRef/UPObase-like diversity), filter for coverage and identity to avoid near-duplicates.
  - Build MSA (A3M) and compute per-position conservation/entropy.
  - Create an initial **protected list** (e.g., entropy < 0.3) to be refined after structure mapping.
- **Outputs:** `homologs.fasta`, `upo_alignment.a3m`, `conservation.json`, `state_step2.json`.
- **If search fails/empty (fallback):** proceed with seed-only alignment; mark lower confidence but continue.

---

### Step 3 — Structure prediction + heme-site sanity + binding_pocket_analysis + docking
**Goal:** convert sequence priors into structure-mapped, actionable mutation sites (channel/pocket) and substrate pose hypotheses.
- **Tools/models:** **Boltz‑2** (structure prediction + docking/pose assessment); **binding_pocket_analysis** module.
- **Inputs:** seed FASTA; substrate list (Veratryl alcohol, Naphthalene, NBD; ABTS often skipped for docking due to size/charge).
- **Process:**
  - Predict CviUPO structure (`CviUPO_boltz2.pdb`).
  - Run `binding_pocket_analysis` to enumerate:
    - **channel residues**
    - **pocket residues**
    - **distal pocket residues**
    - **heme-proximal cysteine** and other catalytic candidates (to protect)
  - Dock small aromatic probes where SMILES are available (NBD, naphthalene, veratryl alcohol) to sanity-check access/orientation.
- **Outputs:** `CviUPO_boltz2.pdb`, `binding_pocket.json`, `docking_results.json`, `state_step3.json`.
- **If docking is noisy/uninformative (fallback):** rely on pocket/channel residue lists + conservation to choose SSM sites; do not block the campaign.

---

### Step 4 — Round 1: targeted single-mutant library (~48) scored by PLM + stability
**Goal:** maximize information gain per variant by probing a small set of channel/pocket positions with conservative chemistry.
- **Library strategy:** **targeted_mutation_set** (single mutants).
- **Tools/models:** **PLM zero-shot scoring** (ΔlogP plausibility), **Pythia** stability prediction (ΔΔG).
- **Inputs:** WT sequence; `binding_pocket.json`; `conservation.json`.
- **Design logic:**
  - Start from structure-derived **channel/pocket residues**; exclude highly conserved positions (and later exclude catalytic/heme-binding residues).
  - Cap to **≤8 positions** for Round 1 feasibility.
  - Use a **restricted AA set** initially (sterics/polarity tuning without extreme charges) to reduce expression/stability failures.
  - Filter out strongly destabilizing variants (e.g., Pythia ΔΔG > ~3 kcal/mol).
  - Select **~48 variants** (96-well friendly with WT + controls).
- **Outputs:** `round1_targeted_variants.json`, `state_step4.json` (includes Round 1 gate definition).
- **If pocket mapping is empty (fallback):** seed known CviUPO channel hotspots (e.g., **F88/T158 region**) and proceed with the same scoring/filters.

**Round 1 experimental readouts (expected):**
- NBD rate (↑ desired)
- ABTS rate (↓ desired at fixed NBD)
- Naphthalene product ratio (↑ 1‑naphthol, ↓ quinone)
- Expression proxy (e.g., activity in lysate/supernatant) + basic stability/H₂O₂ tolerance screen

---

### Step 5 — Round 1 results ingestion + hotspot selection for Round 2 (Gate 1)
**Goal:** make Round 2 contingent on real selectivity data; choose the smallest set of positions that actually move the objective.
- **Library strategy:** decision step (no library built here).
- **Tools/models:** optional **supervised surrogate** scaffolding (OHE/PLM embeddings) for later; primarily a scoring/triage gate.
- **Inputs:** `round1_experimental_results.csv` (user-provided; expected columns include mutations, NBD_rate, ABTS_rate, naphthol_fraction, quinone_fraction, activity, Tm, H₂O₂_tolerance, expression).
- **Decision gate (Gate 1):**
  - Identify **3–4 hotspot positions** from top-performing single mutants that improve:
    - **peroxygenation:peroxidation** (NBD↑ and/or ABTS↓)
    - and/or **mono-oxidation selectivity** (naphthol↑ vs quinone↓)
  - while maintaining minimum thresholds for activity/expression/stability/H₂O₂ tolerance.
- **Outputs:** `state_step5.json` with `round2_hotspots.selected_positions_for_ssm`.
- **If Round 1 data missing (fallback):** advance conservatively using the Round 1 site list (top 4) to avoid stalling.

---

### Step 6 — Round 2: SSM at hotspots + capped combinatorial set with stability + optional ddG_bind triage (~192) (Gate 2)
**Goal:** (i) fully explore amino-acid identity at validated positions (SSM) and (ii) test epistasis/product-release effects via limited recombination.
- **Library strategy:** **site_saturation_mutagenesis (SSM)** + **combinatorial_library** (capped).
- **Tools/models:** **Pythia** stability; optional **OpenMM/YASARA ddG_bind** (probe ligand) for combinatorial prioritization.
- **Inputs:** WT sequence; hotspot positions from Step 5; structure PDB from Step 3 (if available).
- **Design logic:**
  - **SSM** at up to **4 hotspots** (20 AAs), but **downselect** with stability filter to keep total manageable.
  - Build a **capped combinatorial** set:
    - pairwise combinations of top single mutants
    - a small number of triples (randomized but position-deduplicated)
  - Optional ddG_bind triage against a representative aromatic probe (e.g., **naphthalene**) to prioritize variants likely to maintain productive binding/orientation (used as a *ranking aid*, not a hard gate).
  - Target total size **~192 variants** (≈2×96 plates).
- **Outputs:** `round2_library.json`, `state_step6.json` (Round 2 composition, filters, and Gate 2 criteria).
- **If ddG_bind is too slow/unreliable (fallback):** skip ddG_bind and rank using stability + empirical single-mutant performance + PLM plausibility.

**Round 2 experimental readouts (expected):**
- Same as Round 1, but add stronger emphasis on:
  - **overoxidation suppression** (product ratio time-course if possible)
  - **H₂O₂ tolerance** (residual activity after peroxide challenge)
  - stability (Tm or thermal/solvent half-life) if feasible

---

### Step 7 — Round 3: model-guided recombinant panel (~48) balancing selectivity, activity, stability, H₂O₂ tolerance (Gate 3)
**Goal:** produce a small, high-value final panel by exploiting accumulated labeled data and/or physics/priors.
- **Library strategy:** **targeted recombinant panel** (2–4 mutations) derived from Round 2 winners.
- **Tools/models:** supervised surrogate (OHE/PLM embeddings) **if enough labeled data**; otherwise **PLM + Pythia + optional ddG_bind** ranking.
- **Inputs:** `round2_experimental_results.csv` (if available), WT sequence, structure PDB (optional).
- **Selection logic:**
  - Generate many candidate recombinants from top Round 2 performers.
  - Filter by:
    - stability (Pythia ΔΔG threshold)
    - PLM plausibility (avoid low-likelihood sequences)
    - optional ddG_bind (avoid obvious binding collapse)
  - **If ≥ ~30 labeled Round 2 variants:** train a surrogate on the composite objective (selectivity + activity + stability + H₂O₂ tolerance + expression) and select top ~48 by predicted score.
  - **Else:** rank by priors (ddG_bind, stability, PLM) and select top ~48.
- **Outputs:** `round3_final_panel.json`, `state_step7.json` (includes finalization criteria).

**Gate 3 (finalize leads):**
- Select **3–5 leads** that meet:
  - improved aromatic mono-oxidation selectivity (e.g., naphthol/quinone ↑)
  - reduced peroxidation signature (ABTS ↓ at fixed NBD)
  - maintained catalytic activity and expression
  - acceptable or improved stability and **H₂O₂ tolerance**
  - compatibility with the chosen expression host/workflow

---

### Step 8 — Optional contingency: hybrid channel-loop redesign or backbone switch (only if triggered)
**Goal:** unblock the program if backbone mutagenesis cannot reach the objective frontier.
- **Design mode:** **hybrid** (contingency only).
- **Tools/models:** **RFdiffusion2/BoltzGen** for loop/channel redesign; **PLM** + **Pythia** for filtering.
- **Trigger condition:** user sets `state["user_trigger_hybrid_fallback"]=true` after reviewing Round 2/3 outcomes (e.g., no variants beat WT on selectivity while maintaining activity/stability/expression).
- **Inputs:** structure PDB; defined loop regions (from pocket/channel analysis).
- **Outputs:** `hybrid_redesign_candidates.json` (e.g., top 24 designs), `state_step8.json`.
- **Fallback:** if no reliable structure/loop definition exists, switch strategy to **backbone selection**: choose a better-expressing homolog from Step 2 and restart Round 1 on that backbone.

---

## Decision gates and immediate next actions (short)

- **Gate 0 (now, hard):** Provide **CviUPO FASTA/accession** (must pass Step 1). Confirm **expression host** and confirm you can run **NBD + ABTS** plus at least one **aromatic product ratio** assay (naphthalene preferred).
- **Gate 1 (post-Round 1):** Advance positions/variants that improve **NBD/ABTS** and/or **naphthol/quinone** without major losses in activity/expression/stability/H₂O₂ tolerance; select **3–4 hotspots** for Round 2 SSM.
- **Gate 2 (post-Round 2):** Advance variants that improve **mono-oxidation selectivity** and suppress overoxidation/peroxidation while meeting stability + H₂O₂ tolerance + expression constraints; decide whether enough labeled data exist to justify a surrogate for Round 3.
- **Gate 3 (post-Round 3):** Finalize **3–5 leads**. If none meet the full objective, trigger **Step 8 hybrid fallback** (loop/channel redesign or backbone switch).

### Structured Workflow Plan (Prompt 1 JSON as table)

,step_index,step_name,tools,description,python_code_preview
0,1,initialize_project_state_and_hard_gate_seed_se...,,"Loads user inputs, locates or stubs the CviUPO...","import json, os, re from pathlib import Path ..."
1,2,homolog_mining_msa_and_conservation_with_upoba...,"sequence database search and alignment, conser...","Runs homolog search, builds an MSA, computes p...","import json, os from pathlib import Path OUTD..."
2,3,structure_prediction_heme_site_sanity_and_bind...,Boltz-2 docking/pose assessment,"Predicts CviUPO structure (Boltz-2), runs bind...","import json, os from pathlib import Path OUTD..."
3,4,round1_targeted_single_mutant_library_design_s...,"protein language model zero-shot scoring, Pyth...",Designs a ~48-variant targeted single-mutant l...,"import json, os, re from pathlib import Path ..."
4,5,round1_results_ingestion_and_hotspot_selection...,supervised surrogate models with OHE/PLM embed...,Ingests Round 1 experimental results (if provi...,"import json, os, csv from pathlib import Path ..."
5,6,round2_library_build_ssm_plus_capped_combinato...,"OpenMM/YASARA ddG_bind simulations, Pythia sta...",Builds Round 2 SSM at 3–4 hotspots plus a capp...,"import json, os, re, itertools, random from pa..."
6,7,round3_model_guided_recombinant_panel_balancin...,supervised surrogate models with OHE/PLM embed...,Generates and downselects a ~48-variant Round ...,"import json, os, re, csv, random from pathlib ..."
7,8,optional_fallback_hybrid_channel_loop_redesign...,"BoltzGen or RFdiffusion2 de novo generation, p...",Optional contingency step: redesign channel-li...,"import json, os from pathlib import Path OUTD..."

{'refined_workflow_step_count': 8,
 'design_plan_path': '/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning/design_strategy_planning.md',
 'workflow_steps_path': '/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning/design_strategy_planning_workflow_steps.json'}

## Save Thread Update
Append planning prompt/metadata to `chats/<llm_process_tag>_<thread_id>.json`.

In [8]:
persist_thread_update(
    root_key=root_key,
    thread_id=thread_id,
    user_inputs=user_inputs,
    design_plan_path=out_design_plan,
    design_plan_text=design_plan,
    workflow_steps_path=out_workflow_steps,
    workflow_steps_json=workflow_steps_json,
    literature_context_thread_key=literature_context_thread_key,
)

'2026-03-03T07:24:57.208407+00:00'