# 01_design_strategy_planning

Notebook UI for planning a multi-round enzyme design workflow using user constraints and optional prior literature-review context.

## Python Path Setup
Ensure project-root imports work whether Jupyter starts from repo root or `notebooks/`.

In [1]:
from pathlib import Path
import os
import sys

cwd = Path.cwd().resolve()
repo_root = cwd.parent if cwd.name == "notebooks" else cwd
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
src_root = repo_root / "src"
if src_root.exists() and str(src_root) not in sys.path:
    sys.path.insert(0, str(src_root))

## Imports
Load helper functions for setup, optional literature-context loading, planning prompt generation, and thread persistence.

In [2]:
import importlib
import agentic_protein_design.steps.design_strategy_planning as dsp

dsp = importlib.reload(dsp)
from project_config.local_api_keys import OPENAI_API_KEY

default_user_inputs = dsp.default_user_inputs
init_thread = dsp.init_thread
load_literature_context = dsp.load_literature_context
generate_design_strategy_plan = dsp.generate_design_strategy_plan
reflect_and_regenerate_design_strategy_plan = dsp.reflect_and_regenerate_design_strategy_plan
design_strategy_reflection_prompt = dsp.design_strategy_reflection_prompt
save_design_strategy_plan = dsp.save_design_strategy_plan
save_design_strategy_workflow_steps = dsp.save_design_strategy_workflow_steps
persist_thread_update = dsp.persist_thread_update
setup_data_root = dsp.setup_data_root
get_step_processed_dir = dsp.get_step_processed_dir

from agentic_protein_design.core import apply_notebook_markdown_style

# Slightly smaller rendered markdown text in outputs.
apply_notebook_markdown_style(font_size_px=14, line_height=1.4)

## API Key Setup
Load the OpenAI key from `project_config/local_api_keys.py` into environment variables for LLM calls.

In [3]:
if OPENAI_API_KEY and OPENAI_API_KEY != "REPLACE_WITH_YOUR_OPENAI_API_KEY":
    os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

"OPENAI_API_KEY" in os.environ

True

## User Inputs
Configure dataset root, thread key, optional literature context key, and planning requirements.

In [4]:
root_key = "examples"
existing_thread_key = 'design_strategy_planning_4b3ab33f0d634e4a85ce73f259eda102'

user_inputs = {
    "enzyme_family": "unspecific peroxygenases (UPOs)",
    "seed_sequences": ["CviUPO"],
    "reactions_of_interest": "peroxygenation of aromatics",
    "substrates_of_interest": ["Veratryl alcohol", "Naphthalene", "NBD", "ABTS", "S82"],
    "application_context": "biocatalysis and green chemistry",
    "constraints": ["H2O2 tolerance", "stability", "expression host compatibility"],
    "design_type_preference": "mutants_of_backbone",
    "backbone_protein": "CviUPO",
    "library_types": [
        "targeted_mutation_set",
        "site_saturation_mutagenesis",
        "combinatorial_library",
    ],
    "num_design_rounds": 3,
    "design_targets": [
        "increase peroxygenative mono-oxidation selectivity",
        "reduce over-oxidation",
        "maintain catalytic activity",
        "maintain or improve stability",
    ],
    "use_binding_pocket_analysis_step": True,
    "available_tools": [
        "sequence database search and alignment",
        "conservation_analysis analysis",
        "Boltz-2 docking/pose assessment",
        "OpenMM/YASARA ddG_bind simulations",
        "Pythia stability prediction",
        "protein language model zero-shot scoring",
        "BoltzGen or RFdiffusion2 de novo generation",
        "supervised surrogate models with OHE/PLM embeddings",
    ],
    # Optional: key format is {tag}_{thread_id}, e.g. literature_review_<thread_id>
    "literature_context_thread_key": "literature_review_d762a72ec7f04bec9b66ccd3aac21b91",
    "llm_model": "gpt-5.2",
    "llm_temperature": 0.2,
}

# Optional: reset all fields from helper defaults

## Setup Runtime Context
Initialize data directories and active chat thread from the values above.

In [5]:
data_root, resolved_dirs = setup_data_root(root_key)
step_processed_dir = get_step_processed_dir(resolved_dirs)
thread, threads_preview = init_thread(root_key, existing_thread_key)
thread_id = thread["thread_id"]
data_root, step_processed_dir, thread_id

(PosixPath('/Users/charmainechia/Documents/projects/agentic-protein-design/examples'),
 PosixPath('/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning'),
 '4b3ab33f0d634e4a85ce73f259eda102')

## Optional Literature Context
Load prior literature-review context (thread history + referenced output files) when a thread key is provided.

In [6]:
literature_context_thread_key = str(user_inputs.get("literature_context_thread_key", "")).strip() or None
context_result = load_literature_context(literature_context_thread_key, max_chars_per_file=20000)
literature_context = str(context_result.get("context_text", ""))
literature_context_bundle = context_result.get("context_bundle")
len(literature_context), context_result.get("context_error", "")

(88579, '')

## Generate Design Strategy Plan
Run planning LLM call using user requirements and optional literature context, then save markdown output.

In [7]:
plan_outputs = generate_design_strategy_plan(
    user_inputs,
    literature_context=literature_context,
)
design_plan = plan_outputs['strategy_writeup']
workflow_steps_json = plan_outputs['workflow_steps_json']

# Save/overwrite both artifacts from initial generation.
out_design_plan = save_design_strategy_plan(design_plan, step_processed_dir)
out_workflow_steps = save_design_strategy_workflow_steps(workflow_steps_json, step_processed_dir)

{
    "workflow_step_count": len(workflow_steps_json),
    "has_strategy_writeup": bool(design_plan.strip()),
    "design_plan_path": str(out_design_plan),
    "workflow_steps_path": str(out_workflow_steps),
}

### Design Strategy LLM Call (Prompt 2 Writeup)

<details><summary>Prompt</summary>

```text

You are an expert computational protein engineer and workflow architect.

Goal:
Convert project requirements into an executable multi-step protein-design workflow.

Inputs:
- user_inputs_json: project requirements and design preferences
- literature_context (optional): prior literature synthesis and linked full-text summaries

Requirements:
1) Build an end-to-end strategy with clear phases (data, hypothesis, design, evaluation, iteration).
2) Explicitly choose and justify design mode:
   - de novo design, backbone-focused mutant design, or hybrid
3) Propose library strategy aligned to objectives:
   - exact targeted sequences, random mutagenesis, site-saturation mutagenesis (SSM), combinatorial library
4) Plan across the specified number of rounds and approximate size of each round, with clear decision gates and progression criteria.
5) Include concrete implementation details:
   - tools/models to run per step
   - expected inputs/outputs per step
   - fallback or alternative path if a step fails
6) Integrate relevant existing process modules when useful (for example binding_pocket_analysis).
7) Prioritize feasibility, information gain per round, and tractable experimental burden.

Available tool categories (non-exhaustive):
- sequence database search and alignment -> conservation analysis
- receptor-ligand docking / structure prediction (for example Boltz-2)
- ddG_bind style simulations (for example OpenMM or YASARA)
- stability prediction (for example Pythia)
- zero-shot scoring from protein language models
- de novo generation (for example BoltzGen or RFdiffusion2)
- supervised surrogate models (for example OHE/PLM embeddings + constrained acquisition)


PROJECT REQUIREMENTS SNAPSHOT
- enzyme_family: unspecific peroxygenases (UPOs)
- seed_sequences: CviUPO
- reactions_of_interest: peroxygenation of aromatics
- design_type_preference: mutants_of_backbone
- backbone_protein: CviUPO
- library_types: targeted_mutation_set; site_saturation_mutagenesis; combinatorial_library
- num_design_rounds: 3
- design_targets: increase peroxygenative mono-oxidation selectivity; reduce over-oxidation; maintain catalytic activity; maintain or improve stability
- constraints: H2O2 tolerance; stability; expression host compatibility
- available_tools: sequence database search and alignment; conservation analysis; Boltz-2 docking/pose assessment; OpenMM/YASARA ddG_bind simulations; Pythia stability prediction; protein language model zero-shot scoring; BoltzGen or RFdiffusion2 de novo generation; supervised surrogate models with OHE/PLM embeddings



PART 2: Write a concise human-readable strategy summary using:
1) the original context, and
2) the PART 1 JSON workflow.

Output contract:
- Return ONLY markdown prose.
- Keep it succinct and action-oriented (target ~350-700 words).

Required sections:
1. Overall strategy (5-8 bullets)
2. Design choices and assumptions (short)
3. Step-by-step execution summary
   - one compact paragraph per step from PART 1
   - if a step proposes using a foundational Protein Language Model or Structure-prediction model is proposed, recommend which models to use.
   - if a step proposes using a supervised Machine Learning model trained on screening data, propose the model type and input features to use (ok to provide options)
4. Decision gates and immediate next actions (short)

```
</details>

#### Response

(Full strategy shown below in compact view.)

### Human-Readable Strategy (Prompt 2)

## Overall strategy (5–8 bullets)

- Use a **backbone-focused mutant design** campaign on **CviUPO** to tune **access-channel geometry and heme-proximal positioning** that govern aromatic mono-oxidation vs sequential over-oxidation/peroxidation.
- Start with **sequence/structure context** (UPO homolog MSA + conservation + Boltz-2 structure) to avoid disrupting conserved heme-thiolate motifs and to prioritize mutable pocket/channel residues.
- Run an explicit **binding_pocket_analysis** module to enumerate **pocket + tunnel residues**, then use **multi-substrate docking** (naphthalene, veratryl alcohol; plus probes) to identify orientation constraints linked to selectivity.
- Execute **3 experimental rounds** with increasing model/data leverage: **Round 1 targeted set** (single/double mutants) → **Round 2 SSM** at empirically validated hotspots → **Round 3 small combinatorial** library guided by a **supervised surrogate** trained on screening data.
- Maintain feasibility by keeping libraries small (≈48 → per-site SSM → ≈12 final combos) and using **PLM zero-shot + Pythia stability** as early filters to reduce expression/stability failures.
- Track the key tradeoff explicitly: **peroxygenation activity vs peroxidative side chemistry**, using **NBD (peroxygenation proxy)** and **ABTS (peroxidase proxy)** plus product analytics to compute **mono-oxidation selectivity / over-oxidation**.
- Include **process co-optimization hooks** (controlled H₂O₂ dosing, ±ascorbate) as a fallback lever when radical-chain over-oxidation dominates apparent selectivity.

## Design choices and assumptions (short)

- **Design mode:** *mutants_of_backbone* (explicitly preferred). De novo is unnecessary because CviUPO is a functional scaffold; the main objective is **selectivity reprogramming** via channel/pocket reshaping while preserving stability/expression.
- Assumes you can obtain/produce CviUPO sequence and a workable expression/screening setup; if expression is limiting, the workflow pivots to **stability-first** filtering and/or host/signal-peptide optimization (not the main design mode).

## Step-by-step execution summary

**Step 1 — Ingest inputs & fetch seed.** The workflow normalizes requirements and resolves the **CviUPO FASTA** (local file or database). Output is `artifacts/seed.fasta` plus a normalized config. If fetch fails, the immediate action is to provide `data/CviUPO.fasta`.

**Step 2 — MSA + conservation map.** Pull UPO homologs (e.g., UniRef/UPObase-derived sets), build an MSA, and compute per-position conservation/entropy to define a “mutable-but-not-essential” pool. Outputs: `upo_msa.a3m`, `conservation.csv`, and `mutable_positions_initial.csv`. If too few homologs are found, relax search thresholds or switch databases.

**Step 3 — Structure model + binding_pocket_analysis.** Predict a CviUPO structure with **Boltz-2** (recommended for this workflow) and run **binding_pocket_analysis** to list **pocket/channel/heme-proximal residues**, then merge with conservation to rank designable sites. Outputs: `cviupo_model.pdb`, `pocket_map.json`, `pocket_positions_ranked.csv`. If model confidence is low, later steps restrict mutations to high-confidence regions.

**Step 4 — Multi-substrate docking pose triage.** Dock key aromatics (at minimum **naphthalene** and **veratryl alcohol**) with **Boltz-2 docking/pose assessment** and score “productive” heme approach geometries. Outputs: `docking_pose_table.csv` and `docking_pose_summary.csv`. If no productive poses appear, pivot hypotheses toward broader channel opening and/or process levers.

**Step 5 — Round 1 targeted mutation set (≈48 variants).** Generate a tractable set of **single + limited double mutants** at top-ranked pocket/channel sites; score with **PLM zero-shot** (recommend **ESM2** or **ProtT5** for mutation plausibility) + **Pythia** stability + quick redocking proxies. Output: `round1_targeted_variants.csv`. If too few variants pass filters, relax ddG thresholds or expand candidate positions.

**Step 6 — Round 2 SSM (hotspot-focused).** After Round 1 screening, select 3–5 parent variants and choose **6–8 SSM sites** enriched among top performers plus 1–2 exploratory pocket residues. Output: `round2_ssm_sites.csv` and a primer-table template. If Round 1 selectivity gains are weak, pivot SSM toward **peroxygenative:peroxidative ratio hotspots** (alignment to known AaeUPO loop positions) and re-screen under controlled H₂O₂ feed.

**Step 7 — Round 3 combinatorial library + surrogate-guided selection (≈12 constructs).** Train a supervised surrogate on Round 2 data (recommended: **XGBoost** or **ridge regression** on **PLM embeddings**; alternative: OHE on mutated sites) to propose a small combinatorial set (e.g., 4 sites × 3 AAs). Filter with **Pythia**; optionally sanity-check top candidates with **OpenMM/YASARA ddG_bind** on a representative aromatic pose. Outputs: `round3_combinatorial_selected.csv`. If ddG_bind is unstable, fall back to surrogate acquisition + stability filters.

**Step 8 — Decision gates & iteration plan.** The workflow compiles results into `decision_gates_report.json` and triggers pivots: (i) expression/stability-first, (ii) P:p ratio hotspot targeting, (iii) process co-optimization (H₂O₂ dosing, ±ascorbate), depending on which constraint is failing.

## Decision gates and immediate next actions (short)

- **Gate after Round 1:** proceed if ≥1 variant shows **≥1.5× selectivity_mono_over** with acceptable activity/stability; otherwise pivot to P:p hotspots + process controls.
- **Gate after Round 2:** proceed if multiple SSM hits reach **≥2× selectivity** and improved H₂O₂ tolerance; otherwise refine sites and use smart alphabets (reduced degeneracy).
- **Immediate next actions:** provide **CviUPO FASTA**, confirm **expression host**, and define the **selectivity_mono_over** measurement (HPLC/GC product ratio for naphthalene/veratryl alcohol) so Round 1 scoring aligns with the real objective.

### Structured Workflow Plan (Prompt 1 JSON as table)

,step_index,step_name,tools,description,python_code_preview
0,1,ingest_inputs_and_fetch_seed,sequence database search and alignment,"Loads project requirements, resolves the CviUP...","import json, os, re from pathlib import Path ..."
1,2,msa_and_conservation_map,"sequence database search and alignment, conser...","Finds UPO homologs, builds an MSA, computes pe...",import json from pathlib import Path import pa...
2,3,structure_model_and_binding_pocket_analysis,"Boltz-2 docking/pose assessment, conservation ...",Predicts a CviUPO structure model and runs bin...,import json from pathlib import Path import pa...
3,4,multi_substrate_docking_pose_triage,Boltz-2 docking/pose assessment,Docks key aromatic substrates into the CviUPO ...,import json from pathlib import Path import pa...
4,5,round1_targeted_mutation_set_design_and_scoring,"protein language model zero-shot scoring, Pyth...",Generates a Round 1 targeted mutation set (~48...,import json from pathlib import Path import pa...
5,6,round2_ssm_site_selection_and_primer_table,"conservation analysis, Pythia stability predic...","Consumes Round 1 experimental results, selects...",import json from pathlib import Path import pa...
6,7,round3_combinatorial_library_and_surrogate_gui...,supervised surrogate models with OHE/PLM embed...,Trains a supervised surrogate on Round 2 SSM d...,import json from pathlib import Path import pa...
7,8,cross_round_decision_gates_and_iteration_plan,conservation analysis,Aggregates cross-round results (when available...,import json from pathlib import Path import pa...

{'workflow_step_count': 8,
 'has_strategy_writeup': True,
 'design_plan_path': '/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning/design_strategy_planning.md',
 'workflow_steps_path': '/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning/design_strategy_planning_workflow_steps.json'}

## Reflect / Critique and Regenerate Plan

Use this step to critique the initial plan, incorporate optional user feedback, and rewrite a single improved final plan for saving/persistence.

In [8]:
user_feedback = {
    "plan_reflection_user_feedback": "",  # Optional: free-text critique/changes you want the LLM to apply
    "plan_reflection_prompt_override": "",  # Optional: replace default reflection prompt (part 2)
}

reflection_user_feedback = str(user_feedback.get("plan_reflection_user_feedback", "")).strip()
reflection_prompt = str(user_feedback.get("plan_reflection_prompt_override", "")).strip() or design_strategy_reflection_prompt

plan_outputs = reflect_and_regenerate_design_strategy_plan(
    user_inputs=user_inputs,
    original_prompt_1_output=workflow_steps_json,
    original_prompt_2_output=design_plan,
    literature_context=literature_context,
    user_feedback=reflection_user_feedback,
    critique_prompt=reflection_prompt,
)

# Update in-memory copies
design_plan = plan_outputs['strategy_writeup']
workflow_steps_json = plan_outputs['workflow_steps_json']

# Overwrite saved artifacts with improved outputs
out_design_plan = save_design_strategy_plan(design_plan, step_processed_dir)
out_workflow_steps = save_design_strategy_workflow_steps(workflow_steps_json, step_processed_dir)

{
    "refined_workflow_step_count": len(workflow_steps_json),
    "design_plan_path": str(out_design_plan),
    "workflow_steps_path": str(out_workflow_steps),
}

Critique and revisions summary:
- **Made inputs/objectives explicit and machine-readable:** Step 1 now encodes design mode, rounds, targets/constraints, and assay readouts in `config.normalized.json` (and writes `seed.sequence.txt`) to align computational scoring with experimental goals; original focused mainly on fetching/validating FASTA.
- **Removed brittle external dependency:** FASTA resolution shifted to **local-first only** (no stubbed UniProt fetch path) to reduce failure modes and ambiguity about the “source of truth” sequence.
- **Added a concrete “motif safety” mechanism:** Introduced a **protected-position mask** (high conservation) so the workflow actually enforces “don’t mutate catalytic/heme machinery,” fixing the original inconsistency where motif avoidance was stated but not encoded.
- **Improved structural readiness for docking:** Added **heme/active-site annotation** and a “don’t proceed if heme missing/misnamed” safeguard, addressing a common docking failure mode not handled in the original.
- **Clarified docking success criteria:** Standardized “productive pose” assessment with explicit geometry thresholds (distance/angle) and clearer gating/warnings, making pose triage more actionable than the earlier, looser productive-pose proxy.
- **Strengthened round-to-round decision logic and pivots:** Gates were tightened and made more UPO-specific (selectivity + H₂O₂ tolerance emphasis; smart-alphabet pivot from NNK), and reporting now separates **pivots** vs **recommended next actions** to prevent over-investing in uninformative rounds.

### Design Strategy Reflection / Rewrite

<details><summary>Prompt</summary>

```text

You are an expert computational protein engineer and workflow architect.

Goal:
Convert project requirements into an executable multi-step protein-design workflow.

Inputs:
- user_inputs_json: project requirements and design preferences
- literature_context (optional): prior literature synthesis and linked full-text summaries

Requirements:
1) Build an end-to-end strategy with clear phases (data, hypothesis, design, evaluation, iteration).
2) Explicitly choose and justify design mode:
   - de novo design, backbone-focused mutant design, or hybrid
3) Propose library strategy aligned to objectives:
   - exact targeted sequences, random mutagenesis, site-saturation mutagenesis (SSM), combinatorial library
4) Plan across the specified number of rounds and approximate size of each round, with clear decision gates and progression criteria.
5) Include concrete implementation details:
   - tools/models to run per step
   - expected inputs/outputs per step
   - fallback or alternative path if a step fails
6) Integrate relevant existing process modules when useful (for example binding_pocket_analysis).
7) Prioritize feasibility, information gain per round, and tractable experimental burden.

Available tool categories (non-exhaustive):
- sequence database search and alignment -> conservation analysis
- receptor-ligand docking / structure prediction (for example Boltz-2)
- ddG_bind style simulations (for example OpenMM or YASARA)
- stability prediction (for example Pythia)
- zero-shot scoring from protein language models
- de novo generation (for example BoltzGen or RFdiffusion2)
- supervised surrogate models (for example OHE/PLM embeddings + constrained acquisition)


PROJECT REQUIREMENTS SNAPSHOT
- enzyme_family: unspecific peroxygenases (UPOs)
- seed_sequences: CviUPO
- reactions_of_interest: peroxygenation of aromatics
- design_type_preference: mutants_of_backbone
- backbone_protein: CviUPO
- library_types: targeted_mutation_set; site_saturation_mutagenesis; combinatorial_library
- num_design_rounds: 3
- design_targets: increase peroxygenative mono-oxidation selectivity; reduce over-oxidation; maintain catalytic activity; maintain or improve stability
- constraints: H2O2 tolerance; stability; expression host compatibility
- available_tools: sequence database search and alignment; conservation analysis; Boltz-2 docking/pose assessment; OpenMM/YASARA ddG_bind simulations; Pythia stability prediction; protein language model zero-shot scoring; BoltzGen or RFdiffusion2 de novo generation; supervised surrogate models with OHE/PLM embeddings



You are reviewing previously generated planning artifacts:
1) a human-readable strategy writeup (Prompt 2 output), and
2) a structured workflow JSON list (Prompt 1 output).

Task:
1) Critique consistency and quality across both artifacts:
   - gaps, weak assumptions, missing decision gates, feasibility risks
   - mismatches between workflow JSON steps and writeup narrative
   - missing or unclear implementation details in either artifact
2) Incorporate explicit user feedback if provided.
3) Regenerate an improved human-readable plan that is aligned with the workflow JSON.

Important output constraint:
- Return ONLY the rewritten final plan.
- Do NOT include a separate critique section.
- Do NOT include "old plan vs new plan" comparison.
- Keep the same overall output structure used for design strategy planning.

```
</details>

#### Response

(Refined strategy shown below in compact view.)

### Refined Strategy (After Reflection)

## Overall strategy (5–8 bullets)

- Use a **backbone-focused mutant design** campaign on **CviUPO** to tune **heme access-channel geometry and heme-proximal positioning** that govern aromatic **mono-oxidation selectivity** vs **sequential over-oxidation/peroxidation**.
- Build a **sequence/structure prior** (UPO homolog MSA + conservation + structure model) to (i) **protect catalytic/heme-thiolate machinery**, (ii) prioritize **mutable pocket/channel residues**, and (iii) reduce the risk of expression/activity collapse.
- Run an explicit **binding_pocket_analysis** module to enumerate **pocket + tunnel residues**, then use **multi-substrate docking** (naphthalene, veratryl alcohol; plus probes) to generate **productive-pose geometry metrics** that translate into mutation hypotheses.
- Execute **3 experimental rounds** with increasing data leverage and decreasing library size:
  **Round 1 targeted set** (single + limited double mutants) → **Round 2 SSM** at empirically validated hotspots → **Round 3 small combinatorial** library guided by a **supervised surrogate** trained on Round 2 screening data.
- Keep experimental burden tractable by using early **PLM zero-shot** + **Pythia stability** filters and by capping Round 1 to ~48 constructs; Round 3 to ~12 constructs.
- Track the key tradeoff explicitly: **peroxygenation vs peroxidation** using **NBD (peroxygenation proxy)** and **ABTS (peroxidase proxy)** plus **product analytics** (e.g., naphthalene → naphthol vs naphthoquinone) to compute **selectivity_mono_over**.
- Include **process co-optimization hooks** (controlled H₂O₂ feed; ±ascorbate) as a defined pivot when radical-chain over-oxidation dominates apparent selectivity (supported by UPO literature).

---

## Design choices and assumptions (short)

- **Design mode (explicit):** **mutants_of_backbone** (CviUPO). Justification: the scaffold is already functional; the objective is **selectivity reprogramming** (orientation + access control) while preserving **activity, stability, H₂O₂ tolerance, and expression compatibility**. De novo generation (BoltzGen/RFdiffusion2) is kept as a *non-primary fallback* only if the backbone proves non-expressing or structurally unreliable.
- **Library strategy (explicit):**
  1) **Targeted mutation set** (Round 1): information-rich singles + a few doubles to probe epistasis.
  2) **SSM** (Round 2): saturate 6–8 sites chosen from Round 1 winners + pocket ranking.
  3) **Combinatorial library** (Round 3): 4 sites × top 3 AAs/site (~81 in silico), downselected to ~12 constructs for synthesis.
- Assumes you can provide **CviUPO FASTA locally** and can run a screening stack that yields: expression proxy, NBD activity, ABTS activity, product ratio/selectivity, H₂O₂ tolerance, and a stability readout (Tm/thermal shift).

---

## Step-by-step execution summary

### Step 1 — Ingest inputs, resolve backbone, define objectives
- **Tools/models:** sequence DB search/alignment (optional fetch); local FASTA validation.
- **Inputs:** `INPUT_DATA_JSON.json`, `data/CviUPO.fasta` (or `data/seed.fasta`).
- **Outputs:**
  - `artifacts/seed.fasta`, `artifacts/seed.sequence.txt`
  - `artifacts/config.normalized.json` (objectives + assay readouts placeholders)
- **Gate / failure mode:** if FASTA not found/invalid → provide `data/CviUPO.fasta` and rerun.

### Step 2 — Homolog retrieval, MSA, conservation, and motif safety mask
- **Tools/models:** sequence database search + alignment; conservation analysis.
- **Inputs:** `artifacts/seed.fasta`
- **Outputs:**
  - `artifacts/upo_msa.a3m`, `artifacts/conservation.csv`
  - `artifacts/mutable_positions_initial.csv` (non-protected, moderately conserved positions)
  - `artifacts/upo_hits.json` (traceability)
- **Implementation note:** the workflow encodes a **protected-position mask** (high conservation) to avoid mutating core catalytic machinery; refine later with curated UPO motifs if available.
- **Fallback:** if <100 homologs → relax thresholds / switch db (UniRef50) per step logic.

### Step 3 — Structure prediction, heme annotation, and binding_pocket_analysis
- **Tools/models:** Boltz-2 structure prediction; conservation merge; **binding_pocket_analysis** module.
- **Inputs:** `artifacts/seed.fasta`, `artifacts/conservation.csv`
- **Outputs:**
  - `artifacts/cviupo_model.pdb`, `artifacts/structure_metrics.json`
  - `artifacts/active_site_annotation.json` (heme + key residues)
  - `artifacts/pocket_map.json`, `artifacts/pocket_positions_ranked.csv`
- **Gate:** if model confidence low (e.g., pLDDT_mean < 70) → restrict mutations to high-confidence regions and emphasize conservation-safe sites; optionally generate an alternative model (same step, different settings) before proceeding.
- **Fallback:** if heme annotation fails/missing heme naming → fix heme placement/naming before docking (do not proceed with docking on a heme-less model).

### Step 4 — Multi-substrate docking and productive-pose geometry metrics
- **Tools/models:** Boltz-2 docking/pose assessment.
- **Inputs:** `artifacts/cviupo_model.pdb`, `artifacts/active_site_annotation.json`
- **Outputs:**
  - `artifacts/docking_pose_table.csv`, `artifacts/docking_pose_summary.csv`
  - `artifacts/docking_warning.txt` if key aromatics have zero productive poses
- **Decision use:** identify which channel/pocket residues likely control (i) aromatic approach distance/angle to the oxo, (ii) binding modes that enable **sequential oxidation**.
- **Fallback/pivot:** if no productive poses for naphthalene/veratryl alcohol → broaden hypotheses toward channel entrance opening and/or rely more heavily on Round 1 empirical mapping; also consider process levers (controlled H₂O₂ feed) during screening to reduce confounding overoxidation.

### Step 5 — Round 1 targeted mutation set (single + limited double mutants), scoring, selection
- **Library type:** **targeted_mutation_set**
- **Planned size:** score ~96 in silico → **select ~48** for synthesis/testing (with a warning gate if <24 pass filters).
- **Tools/models:** PLM zero-shot scoring; Pythia stability; quick docking proxy.
- **Inputs:** `artifacts/pocket_positions_ranked.csv`, `artifacts/seed.sequence.txt`, `artifacts/cviupo_model.pdb`
- **Outputs:**
  - `artifacts/round1_all_scored.csv` (full table)
  - `artifacts/round1_targeted_variants.csv` (selected set)
  - `artifacts/round1_gate_warning.txt` if selection collapses
- **Selection logic (encoded):** prioritize variants with improved productive-pose proxies across aromatics, while filtering for stability/expression plausibility (Pythia ddG, PLM delta).
- **Fallback:** if too few pass → relax thresholds (e.g., ddG<3.0), expand candidate positions beyond top 18, or switch to a smarter reduced alphabet at fewer sites.

### Step 6 — Round 1 results ingestion, parent selection, and Round 2 SSM site plan
- **Library type:** **SSM** (site-saturation mutagenesis)
- **Planned size:** **6–8 sites**; practical screening size depends on codon scheme (NNK vs smart alphabets). Start with NNK in the plan, but be ready to reduce degeneracy if burden is high.
- **Tools/models:** conservation context; PLM/Pythia available for optional prefiltering of SSM amino-acid sets.
- **Inputs:**
  - `artifacts/round1_targeted_variants.csv`
  - Wet-lab filled: `artifacts/round1_experimental_results.csv`
- **Outputs:**
  - `artifacts/round2_selected_parents.json` (top ~4 parents)
  - `artifacts/round2_ssm_sites.csv` (sites + codon plan)
  - `artifacts/round2_pivot_note.txt` if selectivity gains are weak
- **Gate:** if best `selectivity_mono_over` < ~1.5× after Round 1 → pivot Round 2 toward **P:p ratio control hotspots** (alignment-mapped equivalents of known loop positions) and enforce controlled H₂O₂ dosing during screens to decouple intrinsic selectivity from peroxide-driven artifacts.

### Step 7 — Round 2 results → surrogate training → Round 3 small combinatorial design + ddG_bind sanity check
- **Library type:** **combinatorial_library** (small, model-guided)
- **Planned size:** generate **~81** combinations in silico (4 sites × 3 AAs) → filter → **simulate top ~24** with ddG_bind if available → **select ~12** constructs for synthesis/testing.
- **Tools/models:** supervised surrogate (PLM/OHE embeddings); PLM zero-shot optional; Pythia stability; OpenMM/YASARA ddG_bind (optional sanity check).
- **Inputs:**
  - Wet-lab filled: `artifacts/round2_ssm_results.csv`
  - `artifacts/seed.fasta`, `artifacts/seed.sequence.txt`, `artifacts/cviupo_model.pdb`
- **Outputs:**
  - `artifacts/round3_combinatorial_ranked_top200.csv`
  - `artifacts/round3_combinatorial_selected.csv` (final ~12)
  - `artifacts/round3_ddgbind_fallback.txt` if ddG_bind fails/unavailable
- **Fallback:** if ddG_bind is unstable or too sparse → select by surrogate acquisition + stability filters only (explicitly encoded).

### Step 8 — Cross-round decision gates, reporting, and failure-mode pivots
- **Tools/models:** conservation analysis (contextual); reporting logic.
- **Inputs:** `artifacts/round1_experimental_results.csv` and/or `artifacts/round2_ssm_results.csv` (if present)
- **Outputs:** `artifacts/decision_gates_report.json` with:
  - Gate summaries (coverage, best selectivity, best H₂O₂ tolerance)
  - Pivot triggers (low coverage, no selectivity, few hits)
  - Recommended next actions (UPO-specific process levers)
- **Core progression criteria (edit to match assay scaling):**
  - **After Round 1:** proceed if ≥1 variant reaches ~**1.5×** selectivity with acceptable activity and H₂O₂ tolerance; otherwise pivot to P:p hotspots + process controls.
  - **After Round 2:** proceed if multiple hits reach **≥2×** selectivity and improved tolerance; otherwise refine sites and reduce degeneracy (smart alphabets), add second-shell/channel-entrance residues.
  - **After Round 3:** target **≥3×** selectivity with stability floor (e.g., Tm ≥45 °C) and no catastrophic activity loss.

---

## Decision gates and immediate next actions (short)

- **Immediate next actions to execute Step 1–4 cleanly:**
  1) Provide `data/CviUPO.fasta` (exact sequence used experimentally).
  2) Confirm **expression host** and secretion format (important for interpreting “expression proxy” and for library feasibility).
  3) Define how **selectivity_mono_over** is computed for naphthalene/veratryl alcohol (HPLC/GC product ratio; include overoxidation products like naphthoquinone).
- **Operational controls to run alongside all rounds (high leverage for UPOs):**
  - Screen under **controlled H₂O₂ feed** (avoid bolus) to reduce inactivation and radical-chain artifacts.
  - Screen **±ascorbate (or another radical scavenger)** to distinguish intrinsically less-peroxidative variants from process-suppressed outcomes.
  - Track **NBD vs ABTS** concurrently to quantify the **peroxygenation/peroxidation balance** while maintaining catalytic activity and stability constraints.

### Structured Workflow Plan (Prompt 1 JSON as table)

,step_index,step_name,tools,description,python_code_preview
0,1,ingest_inputs_resolve_backbone_and_define_obje...,sequence database search and alignment,"Load user requirements, resolve the CviUPO bac...","import json, re from pathlib import Path INPU..."
1,2,homolog_retrieval_msa_conservation_and_motif_s...,"sequence database search and alignment, conser...","Search UPO homologs, build an MSA, compute per...",import json from pathlib import Path import pa...
2,3,structure_prediction_heme_annotation_and_bindi...,"Boltz-2 docking/pose assessment, conservation ...","Predict a CviUPO structure, annotate heme and ...",import json from pathlib import Path import pa...
3,4,multi_substrate_docking_and_productive_pose_ge...,Boltz-2 docking/pose assessment,Dock aromatic substrates and probes into the C...,import json from pathlib import Path import pa...
4,5,round1_targeted_mutation_set_single_double_mut...,"protein language model zero-shot scoring, Pyth...",Generate a tractable Round 1 targeted mutation...,"import json, itertools, re from pathlib import..."
5,6,round1_results_ingestion_parent_selection_and_...,"conservation analysis, protein language model ...","Ingest Round 1 experimental results, select to...","import json, re from pathlib import Path impor..."
6,7,round2_results_surrogate_training_and_round3_s...,supervised surrogate models with OHE/PLM embed...,Train a supervised surrogate model on Round 2 ...,"import json, re, itertools from pathlib import..."
7,8,cross_round_decision_gates_reporting_and_failu...,conservation analysis,Aggregate available experimental results acros...,import json from pathlib import Path import pa...

{'refined_workflow_step_count': 8,
 'design_plan_path': '/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning/design_strategy_planning.md',
 'workflow_steps_path': '/Users/charmainechia/Documents/projects/agentic-protein-design/examples/processed/01_design_strategy_planning/design_strategy_planning_workflow_steps.json'}

## Save Thread Update
Append planning prompt/metadata to `chats/<llm_process_tag>_<thread_id>.json`.

In [9]:
persist_thread_update(
    root_key=root_key,
    thread_id=thread_id,
    user_inputs=user_inputs,
    design_plan_path=out_design_plan,
    design_plan_text=design_plan,
    workflow_steps_path=out_workflow_steps,
    workflow_steps_json=workflow_steps_json,
    literature_context_thread_key=literature_context_thread_key,
)

'2026-02-24T07:54:25.067853+00:00'